name: Tag SubVerso for Verso releases

on:
    push:
        tags:
            - "v4*"
    workflow_dispatch:

jobs:
    sync-tags:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create mising `verso-v*` tags in SubVerso
              run: |
                  ./tag-subverso.sh --push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
